### ISSUE TITLE
Appears to be broken in 10.10

### ISSUE THREAD

**Issue by ylluminate** [nthloop/Objektiv#7] opened 2014-07-28 17:31 UTC
It appears that this is broken in the 10.10 public beta 1.  Presently when I select a browser, I am alerted via the notification service and when I allow it it does not actually change the browser to a new default.

**Comment by bradland** [comment] 2015-01-06 02:07
Objektiv is working for me under 10.10.1, but there is some strangeness in the behavior. I think this happens because of Yosemite's new confirmation message that appears when switching web browsers. Details follow.

Under Yosemite, OS X requires users to confirm any change in default web browser. Upon change, a modal is presented by System Preferences, as seen below:

![screenshot 2015-01-05 20 54 35](https://cloud.githubusercontent.com/assets/2764/5623206/62d34de8-951d-11e4-910d-90eeb2079d0d.png)

This dialog is observed immediately following a browser switch. If you confirm the change, the default browser is changed, but Objektiv reflects the old browser selection until the menu is clicked again.

Specific steps to reproduce:

1. Click the Objektiv and select a different default browser.
2. Click "Use [BROWSER]" in the confirmation dialog.
3. Observe that Objektiv icon does not update.
4. In a terminal, execute: `open http://www.google.com` to confirm browser selection.
5. Click the Objektiv menu again (do not make a selection).
6. Observe that Objektiv icon has updated.

Unfortunately, I'm not a Cocoa dev, so I don't know how to fix this.

**Comment by emechem** [comment] 2015-11-14 21:56
Ah, this actually reflects what I'm seeing in 10.11.1 El Capitan - menu icon doesn't change until clicked, and - confirmation dialog (I didn't know it was the OS that's enforcing this confirmation dialog.  If that's so, ah well. I'll work around it w/ a QuicKeys sequence).

**Comment by Vorror** [comment] 2017-01-09 02:31
I made a fork. Should be fixed with: https://github.com/Vorror/Objektiv/releases

**Comment by cmeury** [comment] 2020-05-15 17:02
Fixed with #17

**Closed by cmeury** 2020-05-15 17:02 UTC
